spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: c_on_user
    password: c_on_pw
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

security:
  jwt:
    token:
      secret-key : g+eEdOe0sEmLsBjdZYam6UbH7FGP9kEKv4P1Jc+RBEE=
      access:
        expire-length : 1800000
      refresh:
        expire-length : 3600000
